# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-24 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DateofReport', models.DateField()),
                ('Process', models.CharField(max_length=100)),
                ('Hours', models.IntegerField()),
            ],
        ),
    ]
