# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-26 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='datesofmonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.DateField()),
            ],
        ),
    ]
